export const GET_TASKS = "GET_TASKS"
export const GET_TASK = "GET_TASK"
export const DEL_TASK = "DEL_TASK"
export const ADD_TASK = "ADD_TASK"
export const OPEN_TASK = "OPEN_TASK"
export const UPDATE_TASK = "UPDATE_TASK"
export const LOAD_TASKS = "LOAD_TASKS"
export const TASK_LOADED = "LOAD_TASK"
export const SWAP_TASKS = "SWAP_TASKS"
export const LOADING_TASK = "LOADING_TASK"
export const CLEAR_DATA = "CLEAR_DATA"
export const OPEN_MINITASK = "OPEN_MINITASK"
export const SWAP_MINITASKS = "SWAP_MINITASKS"
export const LOADING_POINT = "LOADING_POINT"
export const CLOSE_TASK = "CLOSE_TASK"

