export const GET_TASKS = "GET_TASKS"
export const GET_TASK = "GET_TASK"
export const DEL_TASK = "DEL_TASK"
export const ADD_TASK = "ADD_TASK"
export const OPEN_TASK = "OPEN_TASK"
export const UPDATE_TASK = "UPDATE_TASK"
export const LOAD_TASKS = "LOAD_TASKS"
export const LOAD_TASK = "LOAD_TASK"
